apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: job-scheduler
  labels:
    grafana_dashboard: "1"
data:
  job-scheduler-dashboard.json: |
    # Paste the full content of your dashboard.json here
    {
      "id": null,
      "title": "Job Scheduler Overview",
      "schemaVersion": 30,
      "version": 2,
      "panels": [
        { "id": 5, "type": "timeseries", "title": "Jobs Submitted per Minute", "datasource": { "type": "prometheus", "uid": "prometheus" }, "targets": [{ "expr": "sum(rate(jobs_submitted_total[1m])) by (type, priority) * 60", "legendFormat": "{{type}}-{{priority}}", "refId": "A" }], "gridPos": {"h": 8, "w": 24, "x": 0, "y": 0} },
        { "id": 6, "type": "timeseries", "title": "Jobs Processed per Minute", "datasource": { "type": "prometheus", "uid": "prometheus" }, "targets": [{ "expr": "sum(rate(jobs_processed_total[1m])) by (status) * 60", "legendFormat": "{{status}}", "refId": "A" }], "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8} },
        { "id": 4, "type": "stat", "title": "Job Success Rate (%)", "datasource": { "type": "prometheus", "uid": "prometheus" }, "targets": [{ "expr": "100 * sum(rate(jobs_processed_total{status=\"completed\"}[5m])) / sum(rate(jobs_processed_total{status=~\"completed|failed\"}[5m]))", "refId": "A" }], "fieldConfig": { "defaults": { "unit": "percent", "decimals": 2 } }, "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8} },
        { "id": 3, "type": "timeseries", "title": "Avg Job Duration (s)", "datasource": { "type": "prometheus", "uid": "prometheus" }, "targets": [{ "expr": "sum(rate(job_duration_seconds_sum[5m])) by (type) / sum(rate(job_duration_seconds_count[5m])) by (type)", "legendFormat": "{{type}}", "refId": "A" }], "gridPos": {"h": 8, "w": 12, "x": 0, "y": 16} },
        { "id": 11, "type": "stat", "title": "Active Worker Pods", "datasource": { "type": "prometheus", "uid": "prometheus" }, "targets": [{ "expr": "sum(keda_scaled_object_active_replicas{scaled_object=\"worker-scaler\"})", "refId": "A" }], "gridPos": {"h": 8, "w": 12, "x": 12, "y": 16} }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: job-scheduler
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus # Fixed UID for dashboard linking
        type: prometheus
        access: proxy
        url: http://prometheus-proxy.job-scheduler.svc.cluster.local:9090
        isDefault: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: job-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.1.1
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboards
          mountPath: /etc/grafana/provisioning/dashboards
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: job-scheduler
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000 