# TODO: Replace with a managed RDS or a production-ready Postgres Helm chart
# Simple single pod Postgres for demonstration purposes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: job-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "jobs"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: job-scheduler
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432 