apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: job-scheduler
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   '/metrics'
        prometheus.io/port:   '8081'
    spec:
      containers:
      - name: api
        image: placeholder-api-image
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: metrics
          containerPort: 8081
        env:
        - name: DATABASE_URL
          value: "postgres://user:password@postgres.job-scheduler.svc.cluster.local:5432/jobs"
        - name: RABBITMQ_URL
          value: "amqp://user:password@rabbitmq.job-scheduler.svc.cluster.local:5672/"
        - name: DB_MAX_CONNS
          value: "10"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: job-scheduler
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 8081
    targetPort: 8081 