---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-proxy-nginx-conf
  namespace: job-scheduler
  labels:
    app: prometheus-proxy
data:
  default.conf: |
    server {
      listen 9090;

      # Strip /prometheus prefix before proxying
      location /prometheus/ {
        rewrite ^/prometheus/(.*)$ /$1 break;
        # Upstream points to Prometheus service deployed by kube-prometheus-stack Helm chart
        # Service name: <release-name>-kube-prometheus-stack-prometheus in the monitoring namespace
        # (release-name is "prometheus")
        proxy_pass http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/;
        proxy_set_header Host $host;
      }

      # Direct hit to /prometheus (without trailing slash) → redirect to add slash
      location = /prometheus/ {
        return 302 /prometheus/graph;
      }
      location = /prometheus {
        return 301 /prometheus/;
      }

      # Direct hit to /graph (with or without trailing slash) → redirect to Prometheus graph with prefix
      location = /graph {
        return 301 /prometheus/graph;
      }
      location = /graph/ {
        return 302 /prometheus/graph;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-proxy
  namespace: job-scheduler
  labels:
    app: prometheus-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-proxy
  template:
    metadata:
      labels:
        app: prometheus-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-conf
        configMap:
          name: prometheus-proxy-nginx-conf 