global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8081']
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:9091']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672'] 